# This is a basic workflow to help you get started with Actions

name: linux-build-test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      cuda-version:
        description: 'CUDA version. For example: 10.1, 10.2'
        required: true
        default: '10.2'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    container: cuda:${{ github.event.inputs.cuda-version }}-devel-ubuntu18.04
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        ref: universal-cmake   
    # Runs a set of commands using the runners shell
    - name: Install GLM and OpenMP
      run: |
        # GLM: We can get this from the standard Ubuntu repository, any recent version will do
        sudo apt install -y libglm-dev libgomp1
        # TRIMESH: Get dependencies from standard repos, and build project from git using makefile
        sudo apt-get install -y mesa-common-dev libglu1-mesa-dev libxi-dev 
    - name: Clone Trimesh2
      uses: actions/checkout@v2
      with:
        repository: 'Forceflow/trimesh2.git'
        ref: 2020.03.04      
    - name: Build Trimesh2
      run: |
        sudo apt-get install -y mesa-common-dev libglu1-mesa-dev libxi-dev 
        cd trimesh2 && make all -j 2 && cd ..
