# This is a basic workflow to help you get started with Actions

name: windows-build-test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      cuda-version:
        description: 'CUDA version. For example: 10.1, 10.2'
        required: true
        default: '10.2'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-2019
    env:
      CUDA_ARCH: 30
    # The type of runner that the job will run on
    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        ref: universal-cmake  
    # Runs a set of commands using the runners shell
    - name: Install GLM and OpenMP
      run: |
        vcpkg.exe install glm:x64-windows
        vcpkg.exe install openmpi:x64-windows
  
